### ISSUE TITLE
Request: add option to hide tray icon

### ISSUE THREAD

**Issue by ghost** [PhantomGamers/SteamFriendsPatcher#1]
Couple of reasons for this:

1. I like keeping my system tray clean.
2. I often accidentally click the Steam Friends Patcher icon instead of the Steam one.

Not a huge deal but would be nice.

**Comment by PhantomGamers** [comment]
Out of curiosity, what's your use case for this? For example, do you keep the patcher running in your taskbar or do you minimize to tray?

I could add an option to hide the tray icon whilst the program is opened to the taskbar, but I wouldn't want to allow the user to hide the tray icon while the window is hidden because then the only option to exit the program would be to kill it from task manager.

Just checking that this is what you're talking about.

(Well, an alternative solution to that would be to have it so if you attempt to run another instance of the program it shows and focuses the first instance, which I wanted to do anyway, but I've been having trouble trying to implement that.)

**Comment by PhantomGamers** [comment]
I've added the functionality to have the main instance get shown when a new instance is launched here -> 17a769edf7bba8a9b2204f2e65778526a85f8cf8

I'll add the option to hide the tray icon and make it configurable so you can either hide it only when it's not in the tray or hide it altogether. It'll likely be in the next release, which will tentatively be by the end of the weekend.

**Comment by PhantomGamers** [comment]
Added in 0.1.17-beta
