### ISSUE TITLE
This Broke Steam

### ISSUE THREAD

**Issue by CasketPizza** [PhantomGamers/SteamFriendsPatcher#6]
After running this tool, steam crashes constantly at the login screen. even after complete uninstall and registry wipe.
Now I cant use Steam.

**Comment by PhantomGamers** [comment]
With Steam shutdown, deleting `%localappdata%/steam/htmlcache` and `<where you installed steam>Steam/steamui/css/libraryroot.css` and rerunning Steam will ensure you have an installation completely unaffected by this utility.

Running the patcher and using the `Clear Steam Cache` option with the scanner disabled will have the same effect.

If Steam continues to fail to launch, the issue is with Steam and not with the patcher. I suspect this is the case as nothing the patcher does should result in Steam failing to launch, worst case scenario you should see a black window for the library and/or friends list.

**Comment by CasketPizza** [comment]
Wow that response time is gold!
You are 100% correct, sorry for the accusation. I came back to delete my comment (hopefully) before you saw it.
The problem was i was charging my Nintendo controller on my pc, which for some reason fucks it up bigtime D:

**Comment by PhantomGamers** [comment]
No problem, glad it's sorted. If you have any further issues or suggestions feel free to open another issue!
